/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */
var evenFibonacciNumbers = function(maxFibonacciNumber){
	var lastFibonacciNumber = 1;
	var currentFibonacciNumber = 2;
	var newFibonacciNumber;
	var sum = 2;

	while(lastFibonacciNumber + currentFibonacciNumber <= maxFibonacciNumber){
		newFibonacciNumber = lastFibonacciNumber + currentFibonacciNumber;
		if(newFibonacciNumber % 2 === 0){
			sum += newFibonacciNumber;
		}
		lastFibonacciNumber = currentFibonacciNumber;
		currentFibonacciNumber = newFibonacciNumber;
	}
	return sum;
}
console.log(evenFibonacciNumbers(4000000)); // 4613732
